site_name: AF
site_url: https://www.instagram.com
site_author: Aulia Fikri
site_description: "Supplementary Materials for My Thesis"
repo_url: "https://github.com/aulfik/rri_supplementary.github.io"
nav: 
  - Home: index.md
  - About: about.md
theme:
  name: null
  custom_dir: 'cinder/'
  highlightjs: true
  hljs_languages:
    - yaml